packer {
  required_plugins {
    amazon = {
      version = ">= 0.0.2"
      source  = "github.com/hashicorp/amazon"
    }
  }
}

locals {
  timestamp = regex_replace(timestamp(), "[- TZ:]", "")
}

data "amazon-ami" "nga-golden-image" {
  filters = {
    virtualization-type = "hvm"
    name                = "Windows_Server-2022-English-Full-Base-*"
    root-device-type    = "ebs"
  }
  owners      = ["801119661308"]
  most_recent = true
  # Access Region Configuration
  region      = "us-east-1"
}

source "amazon-ebs" "nga-image" {
  region =  "us-east-1"
  source_ami = data.amazon-ami.nga-golden-image.id
  instance_type =  "t2.micro"
  ami_name =  "nga-windows-golden-image-{{timestamp}}"
  # This user data file sets up winrm and configures it so that the connection
  # from Packer is allowed. Without this file being set, Packer will not
  # connect to the instance.
  user_data_file = "./boot_config/autogenerated_password_https_bootstrap.txt"
  communicator = "winrm"
  force_deregister = true
  winrm_insecure = true
  winrm_username = "Administrator"
  winrm_use_ssl = true
}
